# Generated by Django 4.2.1 on 2023-09-18 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_staffs_cline'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffs',
            name='cpassword',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
